---
uint64[] course_id	# a list of pre-registered course ID’s
string[] label		# a list of course labels
uint8 errcode 0
uint8 ERR_NONE=0			# success (no error)
uint8 ERR_UNKNOWN=1			# fail (unknown error / general error)