string cam_id	# camera id
int32 img_w	    # (rectified erp) 이미지의 가로 해상도 (width)
int32 img_h	    # (rectified erp) 이미지의 세로 해상도 (height)
float64 htheta	# rectified erp 이미지의 수평방향각 (unit: radian)
float64 vtheta	# rectified erp 이미지의 수직방향각 (unit: radian)
float64 hfov	# rectified erp 이미지의 수평시야각 (unit: radian)
float64 vfov	# rectified erp 이미지의 수직시야각 (unit: radian)
---
int32 x			# 요청된 카메라 이미지에서의 GP 픽셀좌표
int32 y			# 요청된 카메라 이미지에서의 GP 픽셀좌표
uint8 errcode 0 # error code

uint8 ERR_NONE=0			# success (no error)
uint8 ERR_NO_GP=1			# fail (there is no valid gp or gp is not ready)
uint8 ERR_UNKNOWN_CAMERA=2	# fail ('cam_id' is unknown)
uint8 ERR_UNKNOWN=3			# fail (unknown error / general error)