float64 hfov
float64 theta
---
std_msgs/Header header
GDHDetection2DExt[] detections
uint8 errcode
uint8 ERR_NONE_AND_FIND_SUCCESS=0
uint8 ERR_NONE_AND_FIND_FAILURE=1
uint8 ERR_UNKNOWN=2
uint8 ERR_NOT_INIT_MODEL=3
uint8 ERR_NO_IMAGE=4