uint64 map_id		# global identifier of the pre-built map
---
uint64[] poi_id		# a list of pre-registered PoI ID’s on the map
string[] label		# a list of PoI labels
float64[] latitude	# latitude
float64[] longitude	# logitude
int32[] floor		# floor (0: ground(outdoor), 1: 1st floor(indoor), 2: 2nd floor, …)
uint8 errcode 0
uint8 ERR_NONE=0				# success (no error)
uint8 ERR_UNKNOWN=1			    # fail (unknown error / general error)
uint8 ERR_INVALID_MAP_ID=2		# fail (invalid map id)