# camera: 'theta_cart'
camera: 
  id: "theta_rbq3"
  # htheta_list:
  #   - 90
  #   - 180
  #   - -90
  htheta_list:
   - 180
  hfov: 90

yolo_model:
  conf_threshold: 0.2
  repo: "models/gddemo_v2.1/yolov8x_976_gddemo_v2.1_etri/weights/best.pt"  
  resize_long_px: 1000
  # repo: "models/gd_demo/train958/weights/best.pt"
  # repo: "models/gd_demo/train972_yolov8x/weights/best.pt"
  # repo: "models/gddemo_v2/train967_yolov8m/weights/best.pt"
  use_yoloworld: False
  world_repo: "models/yolov8x-world.pt"

pub_msg:
  subway_gate_each: False
  subway_gate_all: True
  subway_gate_handicap: False

elevator_door_status:
  do_check: False
  depth_repo: "depth-anything/Depth-Anything-V2-Small-hf"

misc:
  draw_gp: False

debug:
  display_yolo: True
  display_cmd_list: False

node_monitor:
  freq_sec: 5.0
  node_wait_sec: 10.0
