# # # camera: 'theta_cart'
camera: 
  id: "theta_rbq3"
  htheta_list:
   # - 90
   # - 180
   # - -90
   - 180
  hfov: 120
  htheta_list_vlm:
   - 180
  hfov_vlm: 90

odom_name: "/gdq/msg/gdq_odom"
# odom_name: "/j100_0778/platform/odom/filtered"

yolo_model:
  conf_threshold: 0.3
  # repo: "models/gd_demo/train958/weights/best.pt"
  # resize_long_px: 1000
  resize_long_px: 1440
  # resize_long_px: 640
  # repo: "models/gd_demo/train972_yolov8x/weights/best.pt"
  # repo: "models/gddemo_v2/train967_yolov8m/weights/best.pt"
  # repo: "models/gddemo_v2/train972_yolov8x/weights/best.pt"
  # repo: "models/gddemo_v2.1/yolov8x_960_gddemo_v2.1_etri_cropaug/weights/best.pt"
  #repo: "models/gddemo_v2.1/yolov8x_976_gddemo_v2.1_etri/weights/best.pt"
  #repo: "models/gddemo_v2.2/train975/weights/best.pt"  
  # repo: "models/gddemo_v2.2/train975_10epoch/weights/last.pt"
  repo: "models/gddemo_v2.3/train_100/weights/last.pt"
  #repo: "models/gddemo_v2.3/train3/weights/last.pt"
  use_yoloworld: False
  world_repo: "models/yoloworld/yolov8x-worldv2.pt"

pub_msg:
  subway_gate_each: False
  subway_gate_all: True
  subway_gate_handicap: False

elevator_door_status:
  do_check: False
  depth_repo: "depth-anything/Depth-Anything-V2-Small-hf"

misc:
  draw_gp: False
  draw_gp_vlm: True
  
debug:
  display_yolo: True
  display_cmd_list: False

node_monitor:
  freq_sec: 5.0
  node_wait_sec: 10.0
  
image_publisher:
  image_folder: "dataset/SA-Bench_v1_sampled/images"
  publish_rate: 1.0
  
vlm:
  server_ip_addr: "http://localhost:8000/v1"
  # server_ip_addr: "http://129.254.87.76:8000/v1"
  model_path: "/workspace/Qwen2.5-VL/sa-vlm/checkpoint-6430_qwen2.5vl-3b_mSAIT_kr"  
  # model_path: "Qwen/Qwen2.5-VL-7B-Instruct"
  # model_path: "Qwen/Qwen2.5-VL-3B-Instruct"
  system_content: "You are a guide dog that delivers information about the surrounding environment to the blind."
  user_content: "Please answer what you see on the floor and translate the whole answer into Korean."
  
openai_whisper:
  WHISPER_MODEL_NAME: "large-v3-turbo"
  MIC_SAMPLE_RATE: 16_000
  ENERGY_THRESHOLD: 1000
  RECORD_TIMEOUT: 2.0
  PHRASE_TIMEOUT: 1.0

STT:
  use_trigger_word: True
  trigger_word: "에디야"
